# This file is part of PyKbd
#
# Copyright (C) 2020  Nulano
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from dataclasses import dataclass
from typing import Optional

from . import _version

__version__ = _version


@dataclass(frozen=True)
class Vk:
    code: int
    name: str
    reserved: bool = False
    """Reserved keys cannot be bound to a VSC."""
    mappable: bool = True
    """Function keys cannot have characters mapped to them."""
    extended: bool = False
    """Must have KBDEXT flag even if mapped to non-prefixed VSC."""
    comment: Optional[str] = None
    fake: bool = False
    """This key was generated by PyKbd and is not defined in Windows SDKs."""

    def __str__(self):
        return f"*{self.name}" if self.fake else self.name

    def __int__(self):
        return self.code
    
    def __lt__(self, other):
        if self.__class__ == other.__class__:
            return (translate(self.code), self.code) < (translate(other.code), other.code)
        return NotImplemented
    
    def __le__(self, other):
        if self.__class__ == other.__class__:
            return (translate(self.code), self.code) <= (translate(other.code), other.code)
        return NotImplemented
    
    def __gt__(self, other):
        if self.__class__ == other.__class__:
            return (translate(self.code), self.code) > (translate(other.code), other.code)
        return NotImplemented
    
    def __ge__(self, other):
        if self.__class__ == other.__class__:
            return (translate(self.code), self.code) >= (translate(other.code), other.code)
        return NotImplemented

    def __eq__(self, other):
        if self.__class__ == other.__class__:
            return self.code == other.code
        return NotImplemented

    def __hash__(self):
        return hash(self.code)

    def __repr__(self):
        r = f"Vk(code={hex(self.code)}, name={repr(self.name)}"
        if self.reserved:
            r += ", reserved=True"
        if not self.mappable:
            r += ", mappable=False"
        if self.extended:
            r += ", extended=True"
        if self.comment is not None:
            r += f", comment={repr(self.comment)}"
        if self.fake:
            r += ", fake=True"
        r += ")"
        return r


_reserved = {
    # mouse cannot be assigned to the keyboard
    "VK_LBUTTON",
    "VK_RBUTTON",
    "VK_MBUTTON",
    "VK_XBUTTON1",
    "VK_XBUTTON2",

    # use VK_L* or VK_R* instead
    "VK_SHIFT",
    "VK_CONTROL",
    "VK_MENU",

    # UI navigation (reserved)
    "VK_NAVIGATION_VIEW",
    "VK_NAVIGATION_MENU",
    "VK_NAVIGATION_UP",
    "VK_NAVIGATION_DOWN",
    "VK_NAVIGATION_LEFT",
    "VK_NAVIGATION_RIGHT",
    "VK_NAVIGATION_ACCEPT",
    "VK_NAVIGATION_CANCEL",

    # Gamepad input
    "VK_GAMEPAD_A",
    "VK_GAMEPAD_B",
    "VK_GAMEPAD_X",
    "VK_GAMEPAD_Y",
    "VK_GAMEPAD_RIGHT_SHOULDER",
    "VK_GAMEPAD_LEFT_SHOULDER",
    "VK_GAMEPAD_LEFT_TRIGGER",
    "VK_GAMEPAD_RIGHT_TRIGGER",
    "VK_GAMEPAD_DPAD_UP",
    "VK_GAMEPAD_DPAD_DOWN",
    "VK_GAMEPAD_DPAD_LEFT",
    "VK_GAMEPAD_DPAD_RIGHT",
    "VK_GAMEPAD_MENU",
    "VK_GAMEPAD_VIEW",
    "VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON",
    "VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON",
    "VK_GAMEPAD_LEFT_THUMBSTICK_UP",
    "VK_GAMEPAD_LEFT_THUMBSTICK_DOWN",
    "VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT",
    "VK_GAMEPAD_LEFT_THUMBSTICK_LEFT",
    "VK_GAMEPAD_RIGHT_THUMBSTICK_UP",
    "VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN",
    "VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT",
    "VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT",
}

_reserved_codes = {
    # after VK_LAUNCH_APP2
    0xB8, 0xB9,
    # after VK_OEM_3
    0xC1, 0xC2,
    # after VK_OEM_8
    0xE0,
    # VK__none_
    0xFF,
}

_function = {
    *_reserved,

    # modifier keys
    "VK_LSHIFT",
    "VK_RSHIFT",
    "VK_LCONTROL",
    "VK_RCONTROL",
    "VK_LMENU",
    "VK_RMENU",
    "VK_LWIN",
    "VK_RWIN",

    # toggle keys
    "VK_CAPITAL",
    "VK_KANA",
    "VK_HANGEUL",
    "VK_HANGUL",
    "VK_IME_ON",
    "VK_JUNJA",
    "VK_FINAL",
    "VK_HANJA",
    "VK_KANJI",
    "VK_IME_OFF",
    "VK_CONVERT",
    "VK_NONCONVERT",
    "VK_ACCEPT",
    "VK_MODECHANGE",
    "VK_NUMLOCK",
    "VK_SCROLL",

    # keys with special function
    "VK_PAUSE",
    "VK_PRIOR",
    "VK_NEXT",
    "VK_END",
    "VK_HOME",
    "VK_LEFT",
    "VK_UP",
    "VK_RIGHT",
    "VK_DOWN",
    "VK_SELECT",
    "VK_PRINT",
    "VK_EXECUTE",
    "VK_SNAPSHOT",
    "VK_INSERT",
    "VK_DELETE",
    "VK_HELP",
    "VK_APPS",
    "VK_SLEEP",

    # function keys
    "VK_F1",
    "VK_F2",
    "VK_F3",
    "VK_F4",
    "VK_F5",
    "VK_F6",
    "VK_F7",
    "VK_F8",
    "VK_F9",
    "VK_F10",
    "VK_F11",
    "VK_F12",
    "VK_F13",
    "VK_F14",
    "VK_F15",
    "VK_F16",
    "VK_F17",
    "VK_F18",
    "VK_F19",
    "VK_F20",
    "VK_F21",
    "VK_F22",
    "VK_F23",
    "VK_F24",

    # media keys
    "VK_BROWSER_BACK",
    "VK_BROWSER_FORWARD",
    "VK_BROWSER_REFRESH",
    "VK_BROWSER_STOP",
    "VK_BROWSER_SEARCH",
    "VK_BROWSER_FAVORITES",
    "VK_BROWSER_HOME",
    "VK_VOLUME_MUTE",
    "VK_VOLUME_DOWN",
    "VK_VOLUME_UP",
    "VK_MEDIA_NEXT_TRACK",
    "VK_MEDIA_PREV_TRACK",
    "VK_MEDIA_STOP",
    "VK_MEDIA_PLAY_PAUSE",
    "VK_LAUNCH_MAIL",
    "VK_LAUNCH_MEDIA_SELECT",
    "VK_LAUNCH_APP1",
    "VK_LAUNCH_APP2",

    # VK_ICO_00 has special handling
    # TODO is KBDSPECIAL needed?
    "VK_ICO_00",
}

KBDEXT = 0x100
KBDMULTIVK = 0x200
KBDSPECIAL = 0x400
KBDNUMPAD = 0x800

_extended = {
    # VK_R* must have KBDEXT to map to correct VK
    "VK_RWIN",
    "VK_RSHIFT",
    "VK_RCONTROL",
    "VK_RMENU",
    # VK_NUMLOCK must have KBDEXT due to VK_PAUSE name conflict
    "VK_NUMLOCK",
}

_multivk_101 = {
    "VK_CONTROL": {
        "VK_NUMLOCK": "VK_PAUSE",
        "VK_SCROLL": "VK_CANCEL",
    },
}

_multivk_84 = {
    "VK_SHIFT": {
        "VK_MULTIPLY": "VK_SNAPSHOT",
    },
    **_multivk_101,
}
_multivk_84["VK_MENU"] = _multivk_84["VK_SHIFT"]

_multivk_ibm102 = {
    "VK_SHIFT": {
        "VK_SCROLL": "VK_CANCEL",
        "VK_NUMLOCK": "VK_PAUSE",
    },
    "VK_CONTROL": {
        "VK_PAUSE": "VK_CANCEL",
        "VK_SCROLL": "VK_CANCEL",
    },
}

_multivk_tbl = {
    "101/102 key (type 4)": _multivk_101,
    "84-86 key (type 3)": _multivk_84,
    # TODO name and type number
    "IBM JP 102": _multivk_ibm102,
}

_multivk = {}


def _multivk_func():
    from collections import defaultdict
    conversions = defaultdict(set)
    for kbd, tbls in _multivk_tbl.items():
        for modifier, tbl in tbls.items():
            for base, conv in tbl.items():
                conversions[base].add(conv)
    for base, lst in conversions.items():
        comment = f"changes to {' or '.join(lst)} with a modifier"
        _multivk[base] = comment


_multivk_func()

_numpad = {
    # TODO is KBDSPECIAL needed?
    "VK_INSERT": "VK_NUMPAD0",
    "VK_END": "VK_NUMPAD1",
    "VK_DOWN": "VK_NUMPAD2",
    "VK_NEXT": "VK_NUMPAD3",
    "VK_LEFT": "VK_NUMPAD4",
    "VK_CLEAR": "VK_NUMPAD5",
    "VK_RIGHT": "VK_NUMPAD6",
    "VK_HOME": "VK_NUMPAD7",
    "VK_UP": "VK_NUMPAD8",
    "VK_PRIOR": "VK_NUMPAD9",
    "VK_DELETE": "VK_DECIMAL",
}

# keys possibly missing from WinUser.h
_extra = {
    Vk(0, "VK__end_", reserved=True, mappable=False, comment="end of keyboard table", fake=True),
    Vk(0x16, "VK_IME_ON", mappable=False),
    Vk(0x1A, "VK_IME_OFF", mappable=False),
    Vk(0xC1, "VK_ABNT_C1", comment="next to Right Shift on Brazillian keyboard"),
    Vk(0xC2, "VK_ABNT_C2", comment="next to Numpad Add on Brazillian keyboard"),
    Vk(0xFF, "VK__none_", reserved=True, mappable=False)
}

_translation = {}
_translation_reverse = {}


def translate(vk):
    """
    Translate KBDMULTIVK or KBDNUMPAD Vk or Vk.code.
    """
    is_vk = isinstance(vk, Vk)
    if not is_vk and not isinstance(vk, int):
        raise TypeError
    vk = _translation.get(vk, int(vk))
    if is_vk:
        vk = code_to_vk[vk]
    return vk


def untranslate(vk):
    """
    Reverse of ``translate()``.
    """
    is_vk = isinstance(vk, Vk)
    if not is_vk and not isinstance(vk, int):
        raise TypeError
    vk = _translation_reverse.get(vk, int(vk))
    if is_vk:
        vk = code_to_vk[vk]
    return vk


def _generate(f, winuser):
    # hide local imports from the generated file
    import re
    import string

    vk = {}

    # VK_0 - VK_9 are same as ASCII, comment only
    # VK_A - VK_Z are same as ASCII, comment only
    for c in string.digits + string.ascii_uppercase:
        name = f"VK_{c}"
        vk[name] = Vk(ord(c), name, fake=True)
    
    matcher = re.compile(r"^[ \t]*"
                         r"#[ \t]*(?:define|DEFINE)"
                         r"[ \t]+(VK_[A-Z0-9_]+)"
                         r"[ \t]+0x([0-9A-F]+)"
                         r"[ \t]*(?:/\*([^*]*)\*/|//(.*))?"
                         r"[ \t]*$")

    for line in winuser:
        m = matcher.match(line)
        if m:
            name, value = m.group(1), int(m.group(2), 16)
            comment = (m.group(3) or m.group(4) or "").strip() or None
            reserved = name in _reserved or value in _reserved_codes
            function = name in _function
            extended = name in _extended
            vk[name] = Vk(value, name, reserved, not function, extended, comment)

    for base, conv in _numpad.items():
        name = f"{conv}_{base[3:]}"
        base_vk = vk[base]
        translated = vk[conv]
        vk[name] = Vk(
            base_vk.code | KBDNUMPAD | KBDSPECIAL,
            name,
            mappable=False,
            comment=f"respects NumLock",
            fake=True,
        )
        _translation[vk[name].code] = translated.code
        _translation_reverse[translated.code] = vk[name].code

    for base, comment in _multivk.items():
        name = f"{base}_MULTIVK"
        base_vk = vk[base]
        vk[name] = Vk(
            base_vk.code | KBDMULTIVK,
            name,
            mappable=False,
            comment=comment,
            fake=True
        )
        _translation[vk[name].code] = base_vk.code
        _translation_reverse[base_vk.code] = vk[name].code

    for extra in _extra:
        if extra.name not in vk:
            vk[extra.name] = extra

    vk = {n: v for n, v in sorted(vk.items(), key=lambda x: x[1])}

    for name, value in vk.items():
        print(f"{name} = {repr(value)}", file=f)
    print(file=f)

    print("all = [", file=f)
    for name in vk:
        print(f"    {name},", file=f)
    print("]", file=f)
    print(file=f)

    print("valid = [", file=f)
    for name, value in vk.items():
        if not value.reserved:
            print(f"    {name},", file=f)
    print("]", file=f)
    print(file=f)

    print("mappable = [", file=f)
    for name, value in vk.items():
        if value.mappable:
            print(f"    {name},", file=f)
    print("]", file=f)
    print(file=f)

    print("name_to_vk = {", file=f)
    for name in vk:
        print(f'    "{name}": {name},', file=f)
    print("}", file=f)
    print(file=f)

    codes = {}
    print("code_to_vk = {", file=f)
    for name, value in vk.items():
        if value.code in codes:
            continue
        codes[value.code] = value
        print(f'    {hex(value.code)}: {name},', file=f)
    print("}", file=f)
    print(file=f)

    print(f"_translation = {repr(_translation)}", file=f)
    print(f"_translation_reverse = {repr(_translation_reverse)}", file=f)


if __name__ == '__main__':
    def _main():
        import sys
        dir, sep, file = __file__.rpartition("_gen_")
        if sep != "_gen_":
            raise RuntimeError("This is the generated file. "
                               "Please run the _gen_ version to regenerate it.")

        if len(sys.argv) != 2:
            raise RuntimeError("Please provide exactly one argument, path to WinUser.h.")

        with open(sys.argv[1], "r", encoding="ascii", errors="strict") as f:
            winuser = f.readlines()

        with open(dir + file, "w", encoding="ascii", errors="strict") as f:
            with open(__file__, "r", encoding="ascii", errors="strict") as s:
                f.write(s.read())
            print(file=f)
            _generate(f, winuser)

    _main()

# ----- start generated content -----

VK__end_ = Vk(code=0x0, name='VK__end_', reserved=True, mappable=False, comment='end of keyboard table', fake=True)
VK_LBUTTON = Vk(code=0x1, name='VK_LBUTTON', reserved=True, mappable=False)
VK_RBUTTON = Vk(code=0x2, name='VK_RBUTTON', reserved=True, mappable=False)
VK_CANCEL = Vk(code=0x3, name='VK_CANCEL')
VK_MBUTTON = Vk(code=0x4, name='VK_MBUTTON', reserved=True, mappable=False, comment='NOT contiguous with L & RBUTTON')
VK_XBUTTON1 = Vk(code=0x5, name='VK_XBUTTON1', reserved=True, mappable=False, comment='NOT contiguous with L & RBUTTON')
VK_XBUTTON2 = Vk(code=0x6, name='VK_XBUTTON2', reserved=True, mappable=False, comment='NOT contiguous with L & RBUTTON')
VK_BACK = Vk(code=0x8, name='VK_BACK')
VK_TAB = Vk(code=0x9, name='VK_TAB')
VK_CLEAR = Vk(code=0xc, name='VK_CLEAR')
VK_RETURN = Vk(code=0xd, name='VK_RETURN')
VK_SHIFT = Vk(code=0x10, name='VK_SHIFT', reserved=True, mappable=False)
VK_CONTROL = Vk(code=0x11, name='VK_CONTROL', reserved=True, mappable=False)
VK_MENU = Vk(code=0x12, name='VK_MENU', reserved=True, mappable=False)
VK_PAUSE = Vk(code=0x13, name='VK_PAUSE', mappable=False)
VK_PAUSE_MULTIVK = Vk(code=0x213, name='VK_PAUSE_MULTIVK', mappable=False, comment='changes to VK_CANCEL with a modifier', fake=True)
VK_CAPITAL = Vk(code=0x14, name='VK_CAPITAL', mappable=False)
VK_KANA = Vk(code=0x15, name='VK_KANA', mappable=False)
VK_HANGEUL = Vk(code=0x15, name='VK_HANGEUL', mappable=False, comment='old name - should be here for compatibility')
VK_HANGUL = Vk(code=0x15, name='VK_HANGUL', mappable=False)
VK_IME_ON = Vk(code=0x16, name='VK_IME_ON', mappable=False)
VK_JUNJA = Vk(code=0x17, name='VK_JUNJA', mappable=False)
VK_FINAL = Vk(code=0x18, name='VK_FINAL', mappable=False)
VK_HANJA = Vk(code=0x19, name='VK_HANJA', mappable=False)
VK_KANJI = Vk(code=0x19, name='VK_KANJI', mappable=False)
VK_IME_OFF = Vk(code=0x1a, name='VK_IME_OFF', mappable=False)
VK_ESCAPE = Vk(code=0x1b, name='VK_ESCAPE')
VK_CONVERT = Vk(code=0x1c, name='VK_CONVERT', mappable=False)
VK_NONCONVERT = Vk(code=0x1d, name='VK_NONCONVERT', mappable=False)
VK_ACCEPT = Vk(code=0x1e, name='VK_ACCEPT', mappable=False)
VK_MODECHANGE = Vk(code=0x1f, name='VK_MODECHANGE', mappable=False)
VK_SPACE = Vk(code=0x20, name='VK_SPACE')
VK_PRIOR = Vk(code=0x21, name='VK_PRIOR', mappable=False)
VK_NEXT = Vk(code=0x22, name='VK_NEXT', mappable=False)
VK_END = Vk(code=0x23, name='VK_END', mappable=False)
VK_HOME = Vk(code=0x24, name='VK_HOME', mappable=False)
VK_LEFT = Vk(code=0x25, name='VK_LEFT', mappable=False)
VK_UP = Vk(code=0x26, name='VK_UP', mappable=False)
VK_RIGHT = Vk(code=0x27, name='VK_RIGHT', mappable=False)
VK_DOWN = Vk(code=0x28, name='VK_DOWN', mappable=False)
VK_SELECT = Vk(code=0x29, name='VK_SELECT', mappable=False)
VK_PRINT = Vk(code=0x2a, name='VK_PRINT', mappable=False)
VK_EXECUTE = Vk(code=0x2b, name='VK_EXECUTE', mappable=False)
VK_SNAPSHOT = Vk(code=0x2c, name='VK_SNAPSHOT', mappable=False)
VK_INSERT = Vk(code=0x2d, name='VK_INSERT', mappable=False)
VK_DELETE = Vk(code=0x2e, name='VK_DELETE', mappable=False)
VK_HELP = Vk(code=0x2f, name='VK_HELP', mappable=False)
VK_0 = Vk(code=0x30, name='VK_0', fake=True)
VK_1 = Vk(code=0x31, name='VK_1', fake=True)
VK_2 = Vk(code=0x32, name='VK_2', fake=True)
VK_3 = Vk(code=0x33, name='VK_3', fake=True)
VK_4 = Vk(code=0x34, name='VK_4', fake=True)
VK_5 = Vk(code=0x35, name='VK_5', fake=True)
VK_6 = Vk(code=0x36, name='VK_6', fake=True)
VK_7 = Vk(code=0x37, name='VK_7', fake=True)
VK_8 = Vk(code=0x38, name='VK_8', fake=True)
VK_9 = Vk(code=0x39, name='VK_9', fake=True)
VK_A = Vk(code=0x41, name='VK_A', fake=True)
VK_B = Vk(code=0x42, name='VK_B', fake=True)
VK_C = Vk(code=0x43, name='VK_C', fake=True)
VK_D = Vk(code=0x44, name='VK_D', fake=True)
VK_E = Vk(code=0x45, name='VK_E', fake=True)
VK_F = Vk(code=0x46, name='VK_F', fake=True)
VK_G = Vk(code=0x47, name='VK_G', fake=True)
VK_H = Vk(code=0x48, name='VK_H', fake=True)
VK_I = Vk(code=0x49, name='VK_I', fake=True)
VK_J = Vk(code=0x4a, name='VK_J', fake=True)
VK_K = Vk(code=0x4b, name='VK_K', fake=True)
VK_L = Vk(code=0x4c, name='VK_L', fake=True)
VK_M = Vk(code=0x4d, name='VK_M', fake=True)
VK_N = Vk(code=0x4e, name='VK_N', fake=True)
VK_O = Vk(code=0x4f, name='VK_O', fake=True)
VK_P = Vk(code=0x50, name='VK_P', fake=True)
VK_Q = Vk(code=0x51, name='VK_Q', fake=True)
VK_R = Vk(code=0x52, name='VK_R', fake=True)
VK_S = Vk(code=0x53, name='VK_S', fake=True)
VK_T = Vk(code=0x54, name='VK_T', fake=True)
VK_U = Vk(code=0x55, name='VK_U', fake=True)
VK_V = Vk(code=0x56, name='VK_V', fake=True)
VK_W = Vk(code=0x57, name='VK_W', fake=True)
VK_X = Vk(code=0x58, name='VK_X', fake=True)
VK_Y = Vk(code=0x59, name='VK_Y', fake=True)
VK_Z = Vk(code=0x5a, name='VK_Z', fake=True)
VK_LWIN = Vk(code=0x5b, name='VK_LWIN', mappable=False)
VK_RWIN = Vk(code=0x5c, name='VK_RWIN', mappable=False, extended=True)
VK_APPS = Vk(code=0x5d, name='VK_APPS', mappable=False)
VK_SLEEP = Vk(code=0x5f, name='VK_SLEEP', mappable=False)
VK_NUMPAD0 = Vk(code=0x60, name='VK_NUMPAD0')
VK_NUMPAD0_INSERT = Vk(code=0xc2d, name='VK_NUMPAD0_INSERT', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD1 = Vk(code=0x61, name='VK_NUMPAD1')
VK_NUMPAD1_END = Vk(code=0xc23, name='VK_NUMPAD1_END', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD2 = Vk(code=0x62, name='VK_NUMPAD2')
VK_NUMPAD2_DOWN = Vk(code=0xc28, name='VK_NUMPAD2_DOWN', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD3 = Vk(code=0x63, name='VK_NUMPAD3')
VK_NUMPAD3_NEXT = Vk(code=0xc22, name='VK_NUMPAD3_NEXT', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD4 = Vk(code=0x64, name='VK_NUMPAD4')
VK_NUMPAD4_LEFT = Vk(code=0xc25, name='VK_NUMPAD4_LEFT', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD5 = Vk(code=0x65, name='VK_NUMPAD5')
VK_NUMPAD5_CLEAR = Vk(code=0xc0c, name='VK_NUMPAD5_CLEAR', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD6 = Vk(code=0x66, name='VK_NUMPAD6')
VK_NUMPAD6_RIGHT = Vk(code=0xc27, name='VK_NUMPAD6_RIGHT', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD7 = Vk(code=0x67, name='VK_NUMPAD7')
VK_NUMPAD7_HOME = Vk(code=0xc24, name='VK_NUMPAD7_HOME', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD8 = Vk(code=0x68, name='VK_NUMPAD8')
VK_NUMPAD8_UP = Vk(code=0xc26, name='VK_NUMPAD8_UP', mappable=False, comment='respects NumLock', fake=True)
VK_NUMPAD9 = Vk(code=0x69, name='VK_NUMPAD9')
VK_NUMPAD9_PRIOR = Vk(code=0xc21, name='VK_NUMPAD9_PRIOR', mappable=False, comment='respects NumLock', fake=True)
VK_MULTIPLY = Vk(code=0x6a, name='VK_MULTIPLY')
VK_MULTIPLY_MULTIVK = Vk(code=0x26a, name='VK_MULTIPLY_MULTIVK', mappable=False, comment='changes to VK_SNAPSHOT with a modifier', fake=True)
VK_ADD = Vk(code=0x6b, name='VK_ADD')
VK_SEPARATOR = Vk(code=0x6c, name='VK_SEPARATOR')
VK_SUBTRACT = Vk(code=0x6d, name='VK_SUBTRACT')
VK_DECIMAL = Vk(code=0x6e, name='VK_DECIMAL')
VK_DECIMAL_DELETE = Vk(code=0xc2e, name='VK_DECIMAL_DELETE', mappable=False, comment='respects NumLock', fake=True)
VK_DIVIDE = Vk(code=0x6f, name='VK_DIVIDE')
VK_F1 = Vk(code=0x70, name='VK_F1', mappable=False)
VK_F2 = Vk(code=0x71, name='VK_F2', mappable=False)
VK_F3 = Vk(code=0x72, name='VK_F3', mappable=False)
VK_F4 = Vk(code=0x73, name='VK_F4', mappable=False)
VK_F5 = Vk(code=0x74, name='VK_F5', mappable=False)
VK_F6 = Vk(code=0x75, name='VK_F6', mappable=False)
VK_F7 = Vk(code=0x76, name='VK_F7', mappable=False)
VK_F8 = Vk(code=0x77, name='VK_F8', mappable=False)
VK_F9 = Vk(code=0x78, name='VK_F9', mappable=False)
VK_F10 = Vk(code=0x79, name='VK_F10', mappable=False)
VK_F11 = Vk(code=0x7a, name='VK_F11', mappable=False)
VK_F12 = Vk(code=0x7b, name='VK_F12', mappable=False)
VK_F13 = Vk(code=0x7c, name='VK_F13', mappable=False)
VK_F14 = Vk(code=0x7d, name='VK_F14', mappable=False)
VK_F15 = Vk(code=0x7e, name='VK_F15', mappable=False)
VK_F16 = Vk(code=0x7f, name='VK_F16', mappable=False)
VK_F17 = Vk(code=0x80, name='VK_F17', mappable=False)
VK_F18 = Vk(code=0x81, name='VK_F18', mappable=False)
VK_F19 = Vk(code=0x82, name='VK_F19', mappable=False)
VK_F20 = Vk(code=0x83, name='VK_F20', mappable=False)
VK_F21 = Vk(code=0x84, name='VK_F21', mappable=False)
VK_F22 = Vk(code=0x85, name='VK_F22', mappable=False)
VK_F23 = Vk(code=0x86, name='VK_F23', mappable=False)
VK_F24 = Vk(code=0x87, name='VK_F24', mappable=False)
VK_NAVIGATION_VIEW = Vk(code=0x88, name='VK_NAVIGATION_VIEW', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_MENU = Vk(code=0x89, name='VK_NAVIGATION_MENU', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_UP = Vk(code=0x8a, name='VK_NAVIGATION_UP', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_DOWN = Vk(code=0x8b, name='VK_NAVIGATION_DOWN', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_LEFT = Vk(code=0x8c, name='VK_NAVIGATION_LEFT', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_RIGHT = Vk(code=0x8d, name='VK_NAVIGATION_RIGHT', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_ACCEPT = Vk(code=0x8e, name='VK_NAVIGATION_ACCEPT', reserved=True, mappable=False, comment='reserved')
VK_NAVIGATION_CANCEL = Vk(code=0x8f, name='VK_NAVIGATION_CANCEL', reserved=True, mappable=False, comment='reserved')
VK_NUMLOCK = Vk(code=0x90, name='VK_NUMLOCK', mappable=False, extended=True)
VK_NUMLOCK_MULTIVK = Vk(code=0x290, name='VK_NUMLOCK_MULTIVK', mappable=False, comment='changes to VK_PAUSE with a modifier', fake=True)
VK_SCROLL = Vk(code=0x91, name='VK_SCROLL', mappable=False)
VK_SCROLL_MULTIVK = Vk(code=0x291, name='VK_SCROLL_MULTIVK', mappable=False, comment='changes to VK_CANCEL with a modifier', fake=True)
VK_OEM_NEC_EQUAL = Vk(code=0x92, name='VK_OEM_NEC_EQUAL', comment="'=' key on numpad")
VK_OEM_FJ_JISHO = Vk(code=0x92, name='VK_OEM_FJ_JISHO', comment="'Dictionary' key")
VK_OEM_FJ_MASSHOU = Vk(code=0x93, name='VK_OEM_FJ_MASSHOU', comment="'Unregister word' key")
VK_OEM_FJ_TOUROKU = Vk(code=0x94, name='VK_OEM_FJ_TOUROKU', comment="'Register word' key")
VK_OEM_FJ_LOYA = Vk(code=0x95, name='VK_OEM_FJ_LOYA', comment="'Left OYAYUBI' key")
VK_OEM_FJ_ROYA = Vk(code=0x96, name='VK_OEM_FJ_ROYA', comment="'Right OYAYUBI' key")
VK_LSHIFT = Vk(code=0xa0, name='VK_LSHIFT', mappable=False)
VK_RSHIFT = Vk(code=0xa1, name='VK_RSHIFT', mappable=False, extended=True)
VK_LCONTROL = Vk(code=0xa2, name='VK_LCONTROL', mappable=False)
VK_RCONTROL = Vk(code=0xa3, name='VK_RCONTROL', mappable=False, extended=True)
VK_LMENU = Vk(code=0xa4, name='VK_LMENU', mappable=False)
VK_RMENU = Vk(code=0xa5, name='VK_RMENU', mappable=False, extended=True)
VK_BROWSER_BACK = Vk(code=0xa6, name='VK_BROWSER_BACK', mappable=False)
VK_BROWSER_FORWARD = Vk(code=0xa7, name='VK_BROWSER_FORWARD', mappable=False)
VK_BROWSER_REFRESH = Vk(code=0xa8, name='VK_BROWSER_REFRESH', mappable=False)
VK_BROWSER_STOP = Vk(code=0xa9, name='VK_BROWSER_STOP', mappable=False)
VK_BROWSER_SEARCH = Vk(code=0xaa, name='VK_BROWSER_SEARCH', mappable=False)
VK_BROWSER_FAVORITES = Vk(code=0xab, name='VK_BROWSER_FAVORITES', mappable=False)
VK_BROWSER_HOME = Vk(code=0xac, name='VK_BROWSER_HOME', mappable=False)
VK_VOLUME_MUTE = Vk(code=0xad, name='VK_VOLUME_MUTE', mappable=False)
VK_VOLUME_DOWN = Vk(code=0xae, name='VK_VOLUME_DOWN', mappable=False)
VK_VOLUME_UP = Vk(code=0xaf, name='VK_VOLUME_UP', mappable=False)
VK_MEDIA_NEXT_TRACK = Vk(code=0xb0, name='VK_MEDIA_NEXT_TRACK', mappable=False)
VK_MEDIA_PREV_TRACK = Vk(code=0xb1, name='VK_MEDIA_PREV_TRACK', mappable=False)
VK_MEDIA_STOP = Vk(code=0xb2, name='VK_MEDIA_STOP', mappable=False)
VK_MEDIA_PLAY_PAUSE = Vk(code=0xb3, name='VK_MEDIA_PLAY_PAUSE', mappable=False)
VK_LAUNCH_MAIL = Vk(code=0xb4, name='VK_LAUNCH_MAIL', mappable=False)
VK_LAUNCH_MEDIA_SELECT = Vk(code=0xb5, name='VK_LAUNCH_MEDIA_SELECT', mappable=False)
VK_LAUNCH_APP1 = Vk(code=0xb6, name='VK_LAUNCH_APP1', mappable=False)
VK_LAUNCH_APP2 = Vk(code=0xb7, name='VK_LAUNCH_APP2', mappable=False)
VK_OEM_1 = Vk(code=0xba, name='VK_OEM_1', comment="';:' for US")
VK_OEM_PLUS = Vk(code=0xbb, name='VK_OEM_PLUS', comment="'+' any country")
VK_OEM_COMMA = Vk(code=0xbc, name='VK_OEM_COMMA', comment="',' any country")
VK_OEM_MINUS = Vk(code=0xbd, name='VK_OEM_MINUS', comment="'-' any country")
VK_OEM_PERIOD = Vk(code=0xbe, name='VK_OEM_PERIOD', comment="'.' any country")
VK_OEM_2 = Vk(code=0xbf, name='VK_OEM_2', comment="'/?' for US")
VK_OEM_3 = Vk(code=0xc0, name='VK_OEM_3', comment="'`~' for US")
VK_ABNT_C1 = Vk(code=0xc1, name='VK_ABNT_C1', comment='next to Right Shift on Brazillian keyboard')
VK_ABNT_C2 = Vk(code=0xc2, name='VK_ABNT_C2', comment='next to Numpad Add on Brazillian keyboard')
VK_GAMEPAD_A = Vk(code=0xc3, name='VK_GAMEPAD_A', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_B = Vk(code=0xc4, name='VK_GAMEPAD_B', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_X = Vk(code=0xc5, name='VK_GAMEPAD_X', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_Y = Vk(code=0xc6, name='VK_GAMEPAD_Y', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_SHOULDER = Vk(code=0xc7, name='VK_GAMEPAD_RIGHT_SHOULDER', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_SHOULDER = Vk(code=0xc8, name='VK_GAMEPAD_LEFT_SHOULDER', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_TRIGGER = Vk(code=0xc9, name='VK_GAMEPAD_LEFT_TRIGGER', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_TRIGGER = Vk(code=0xca, name='VK_GAMEPAD_RIGHT_TRIGGER', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_DPAD_UP = Vk(code=0xcb, name='VK_GAMEPAD_DPAD_UP', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_DPAD_DOWN = Vk(code=0xcc, name='VK_GAMEPAD_DPAD_DOWN', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_DPAD_LEFT = Vk(code=0xcd, name='VK_GAMEPAD_DPAD_LEFT', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_DPAD_RIGHT = Vk(code=0xce, name='VK_GAMEPAD_DPAD_RIGHT', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_MENU = Vk(code=0xcf, name='VK_GAMEPAD_MENU', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_VIEW = Vk(code=0xd0, name='VK_GAMEPAD_VIEW', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON = Vk(code=0xd1, name='VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = Vk(code=0xd2, name='VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_THUMBSTICK_UP = Vk(code=0xd3, name='VK_GAMEPAD_LEFT_THUMBSTICK_UP', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_THUMBSTICK_DOWN = Vk(code=0xd4, name='VK_GAMEPAD_LEFT_THUMBSTICK_DOWN', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT = Vk(code=0xd5, name='VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_LEFT_THUMBSTICK_LEFT = Vk(code=0xd6, name='VK_GAMEPAD_LEFT_THUMBSTICK_LEFT', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_THUMBSTICK_UP = Vk(code=0xd7, name='VK_GAMEPAD_RIGHT_THUMBSTICK_UP', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN = Vk(code=0xd8, name='VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = Vk(code=0xd9, name='VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT', reserved=True, mappable=False, comment='reserved')
VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT = Vk(code=0xda, name='VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT', reserved=True, mappable=False, comment='reserved')
VK_OEM_4 = Vk(code=0xdb, name='VK_OEM_4', comment="'[{' for US")
VK_OEM_5 = Vk(code=0xdc, name='VK_OEM_5', comment="'\\|' for US")
VK_OEM_6 = Vk(code=0xdd, name='VK_OEM_6', comment="']}' for US")
VK_OEM_7 = Vk(code=0xde, name='VK_OEM_7', comment='\'\'"\' for US')
VK_OEM_8 = Vk(code=0xdf, name='VK_OEM_8')
VK_OEM_AX = Vk(code=0xe1, name='VK_OEM_AX', comment="'AX' key on Japanese AX kbd")
VK_OEM_102 = Vk(code=0xe2, name='VK_OEM_102', comment='"<>" or "\\|" on RT 102-key kbd.')
VK_ICO_HELP = Vk(code=0xe3, name='VK_ICO_HELP', comment='Help key on ICO')
VK_ICO_00 = Vk(code=0xe4, name='VK_ICO_00', mappable=False, comment='00 key on ICO')
VK_PROCESSKEY = Vk(code=0xe5, name='VK_PROCESSKEY')
VK_ICO_CLEAR = Vk(code=0xe6, name='VK_ICO_CLEAR')
VK_PACKET = Vk(code=0xe7, name='VK_PACKET')
VK_OEM_RESET = Vk(code=0xe9, name='VK_OEM_RESET')
VK_OEM_JUMP = Vk(code=0xea, name='VK_OEM_JUMP')
VK_OEM_PA1 = Vk(code=0xeb, name='VK_OEM_PA1')
VK_OEM_PA2 = Vk(code=0xec, name='VK_OEM_PA2')
VK_OEM_PA3 = Vk(code=0xed, name='VK_OEM_PA3')
VK_OEM_WSCTRL = Vk(code=0xee, name='VK_OEM_WSCTRL')
VK_OEM_CUSEL = Vk(code=0xef, name='VK_OEM_CUSEL')
VK_OEM_ATTN = Vk(code=0xf0, name='VK_OEM_ATTN')
VK_OEM_FINISH = Vk(code=0xf1, name='VK_OEM_FINISH')
VK_OEM_COPY = Vk(code=0xf2, name='VK_OEM_COPY')
VK_OEM_AUTO = Vk(code=0xf3, name='VK_OEM_AUTO')
VK_OEM_ENLW = Vk(code=0xf4, name='VK_OEM_ENLW')
VK_OEM_BACKTAB = Vk(code=0xf5, name='VK_OEM_BACKTAB')
VK_ATTN = Vk(code=0xf6, name='VK_ATTN')
VK_CRSEL = Vk(code=0xf7, name='VK_CRSEL')
VK_EXSEL = Vk(code=0xf8, name='VK_EXSEL')
VK_EREOF = Vk(code=0xf9, name='VK_EREOF')
VK_PLAY = Vk(code=0xfa, name='VK_PLAY')
VK_ZOOM = Vk(code=0xfb, name='VK_ZOOM')
VK_NONAME = Vk(code=0xfc, name='VK_NONAME')
VK_PA1 = Vk(code=0xfd, name='VK_PA1')
VK_OEM_CLEAR = Vk(code=0xfe, name='VK_OEM_CLEAR')
VK__none_ = Vk(code=0xff, name='VK__none_', reserved=True, mappable=False)

all = [
    VK__end_,
    VK_LBUTTON,
    VK_RBUTTON,
    VK_CANCEL,
    VK_MBUTTON,
    VK_XBUTTON1,
    VK_XBUTTON2,
    VK_BACK,
    VK_TAB,
    VK_CLEAR,
    VK_RETURN,
    VK_SHIFT,
    VK_CONTROL,
    VK_MENU,
    VK_PAUSE,
    VK_PAUSE_MULTIVK,
    VK_CAPITAL,
    VK_KANA,
    VK_HANGEUL,
    VK_HANGUL,
    VK_IME_ON,
    VK_JUNJA,
    VK_FINAL,
    VK_HANJA,
    VK_KANJI,
    VK_IME_OFF,
    VK_ESCAPE,
    VK_CONVERT,
    VK_NONCONVERT,
    VK_ACCEPT,
    VK_MODECHANGE,
    VK_SPACE,
    VK_PRIOR,
    VK_NEXT,
    VK_END,
    VK_HOME,
    VK_LEFT,
    VK_UP,
    VK_RIGHT,
    VK_DOWN,
    VK_SELECT,
    VK_PRINT,
    VK_EXECUTE,
    VK_SNAPSHOT,
    VK_INSERT,
    VK_DELETE,
    VK_HELP,
    VK_0,
    VK_1,
    VK_2,
    VK_3,
    VK_4,
    VK_5,
    VK_6,
    VK_7,
    VK_8,
    VK_9,
    VK_A,
    VK_B,
    VK_C,
    VK_D,
    VK_E,
    VK_F,
    VK_G,
    VK_H,
    VK_I,
    VK_J,
    VK_K,
    VK_L,
    VK_M,
    VK_N,
    VK_O,
    VK_P,
    VK_Q,
    VK_R,
    VK_S,
    VK_T,
    VK_U,
    VK_V,
    VK_W,
    VK_X,
    VK_Y,
    VK_Z,
    VK_LWIN,
    VK_RWIN,
    VK_APPS,
    VK_SLEEP,
    VK_NUMPAD0,
    VK_NUMPAD0_INSERT,
    VK_NUMPAD1,
    VK_NUMPAD1_END,
    VK_NUMPAD2,
    VK_NUMPAD2_DOWN,
    VK_NUMPAD3,
    VK_NUMPAD3_NEXT,
    VK_NUMPAD4,
    VK_NUMPAD4_LEFT,
    VK_NUMPAD5,
    VK_NUMPAD5_CLEAR,
    VK_NUMPAD6,
    VK_NUMPAD6_RIGHT,
    VK_NUMPAD7,
    VK_NUMPAD7_HOME,
    VK_NUMPAD8,
    VK_NUMPAD8_UP,
    VK_NUMPAD9,
    VK_NUMPAD9_PRIOR,
    VK_MULTIPLY,
    VK_MULTIPLY_MULTIVK,
    VK_ADD,
    VK_SEPARATOR,
    VK_SUBTRACT,
    VK_DECIMAL,
    VK_DECIMAL_DELETE,
    VK_DIVIDE,
    VK_F1,
    VK_F2,
    VK_F3,
    VK_F4,
    VK_F5,
    VK_F6,
    VK_F7,
    VK_F8,
    VK_F9,
    VK_F10,
    VK_F11,
    VK_F12,
    VK_F13,
    VK_F14,
    VK_F15,
    VK_F16,
    VK_F17,
    VK_F18,
    VK_F19,
    VK_F20,
    VK_F21,
    VK_F22,
    VK_F23,
    VK_F24,
    VK_NAVIGATION_VIEW,
    VK_NAVIGATION_MENU,
    VK_NAVIGATION_UP,
    VK_NAVIGATION_DOWN,
    VK_NAVIGATION_LEFT,
    VK_NAVIGATION_RIGHT,
    VK_NAVIGATION_ACCEPT,
    VK_NAVIGATION_CANCEL,
    VK_NUMLOCK,
    VK_NUMLOCK_MULTIVK,
    VK_SCROLL,
    VK_SCROLL_MULTIVK,
    VK_OEM_NEC_EQUAL,
    VK_OEM_FJ_JISHO,
    VK_OEM_FJ_MASSHOU,
    VK_OEM_FJ_TOUROKU,
    VK_OEM_FJ_LOYA,
    VK_OEM_FJ_ROYA,
    VK_LSHIFT,
    VK_RSHIFT,
    VK_LCONTROL,
    VK_RCONTROL,
    VK_LMENU,
    VK_RMENU,
    VK_BROWSER_BACK,
    VK_BROWSER_FORWARD,
    VK_BROWSER_REFRESH,
    VK_BROWSER_STOP,
    VK_BROWSER_SEARCH,
    VK_BROWSER_FAVORITES,
    VK_BROWSER_HOME,
    VK_VOLUME_MUTE,
    VK_VOLUME_DOWN,
    VK_VOLUME_UP,
    VK_MEDIA_NEXT_TRACK,
    VK_MEDIA_PREV_TRACK,
    VK_MEDIA_STOP,
    VK_MEDIA_PLAY_PAUSE,
    VK_LAUNCH_MAIL,
    VK_LAUNCH_MEDIA_SELECT,
    VK_LAUNCH_APP1,
    VK_LAUNCH_APP2,
    VK_OEM_1,
    VK_OEM_PLUS,
    VK_OEM_COMMA,
    VK_OEM_MINUS,
    VK_OEM_PERIOD,
    VK_OEM_2,
    VK_OEM_3,
    VK_ABNT_C1,
    VK_ABNT_C2,
    VK_GAMEPAD_A,
    VK_GAMEPAD_B,
    VK_GAMEPAD_X,
    VK_GAMEPAD_Y,
    VK_GAMEPAD_RIGHT_SHOULDER,
    VK_GAMEPAD_LEFT_SHOULDER,
    VK_GAMEPAD_LEFT_TRIGGER,
    VK_GAMEPAD_RIGHT_TRIGGER,
    VK_GAMEPAD_DPAD_UP,
    VK_GAMEPAD_DPAD_DOWN,
    VK_GAMEPAD_DPAD_LEFT,
    VK_GAMEPAD_DPAD_RIGHT,
    VK_GAMEPAD_MENU,
    VK_GAMEPAD_VIEW,
    VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON,
    VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
    VK_GAMEPAD_LEFT_THUMBSTICK_UP,
    VK_GAMEPAD_LEFT_THUMBSTICK_DOWN,
    VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT,
    VK_GAMEPAD_LEFT_THUMBSTICK_LEFT,
    VK_GAMEPAD_RIGHT_THUMBSTICK_UP,
    VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN,
    VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT,
    VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT,
    VK_OEM_4,
    VK_OEM_5,
    VK_OEM_6,
    VK_OEM_7,
    VK_OEM_8,
    VK_OEM_AX,
    VK_OEM_102,
    VK_ICO_HELP,
    VK_ICO_00,
    VK_PROCESSKEY,
    VK_ICO_CLEAR,
    VK_PACKET,
    VK_OEM_RESET,
    VK_OEM_JUMP,
    VK_OEM_PA1,
    VK_OEM_PA2,
    VK_OEM_PA3,
    VK_OEM_WSCTRL,
    VK_OEM_CUSEL,
    VK_OEM_ATTN,
    VK_OEM_FINISH,
    VK_OEM_COPY,
    VK_OEM_AUTO,
    VK_OEM_ENLW,
    VK_OEM_BACKTAB,
    VK_ATTN,
    VK_CRSEL,
    VK_EXSEL,
    VK_EREOF,
    VK_PLAY,
    VK_ZOOM,
    VK_NONAME,
    VK_PA1,
    VK_OEM_CLEAR,
    VK__none_,
]

valid = [
    VK_CANCEL,
    VK_BACK,
    VK_TAB,
    VK_CLEAR,
    VK_RETURN,
    VK_PAUSE,
    VK_PAUSE_MULTIVK,
    VK_CAPITAL,
    VK_KANA,
    VK_HANGEUL,
    VK_HANGUL,
    VK_IME_ON,
    VK_JUNJA,
    VK_FINAL,
    VK_HANJA,
    VK_KANJI,
    VK_IME_OFF,
    VK_ESCAPE,
    VK_CONVERT,
    VK_NONCONVERT,
    VK_ACCEPT,
    VK_MODECHANGE,
    VK_SPACE,
    VK_PRIOR,
    VK_NEXT,
    VK_END,
    VK_HOME,
    VK_LEFT,
    VK_UP,
    VK_RIGHT,
    VK_DOWN,
    VK_SELECT,
    VK_PRINT,
    VK_EXECUTE,
    VK_SNAPSHOT,
    VK_INSERT,
    VK_DELETE,
    VK_HELP,
    VK_0,
    VK_1,
    VK_2,
    VK_3,
    VK_4,
    VK_5,
    VK_6,
    VK_7,
    VK_8,
    VK_9,
    VK_A,
    VK_B,
    VK_C,
    VK_D,
    VK_E,
    VK_F,
    VK_G,
    VK_H,
    VK_I,
    VK_J,
    VK_K,
    VK_L,
    VK_M,
    VK_N,
    VK_O,
    VK_P,
    VK_Q,
    VK_R,
    VK_S,
    VK_T,
    VK_U,
    VK_V,
    VK_W,
    VK_X,
    VK_Y,
    VK_Z,
    VK_LWIN,
    VK_RWIN,
    VK_APPS,
    VK_SLEEP,
    VK_NUMPAD0,
    VK_NUMPAD0_INSERT,
    VK_NUMPAD1,
    VK_NUMPAD1_END,
    VK_NUMPAD2,
    VK_NUMPAD2_DOWN,
    VK_NUMPAD3,
    VK_NUMPAD3_NEXT,
    VK_NUMPAD4,
    VK_NUMPAD4_LEFT,
    VK_NUMPAD5,
    VK_NUMPAD5_CLEAR,
    VK_NUMPAD6,
    VK_NUMPAD6_RIGHT,
    VK_NUMPAD7,
    VK_NUMPAD7_HOME,
    VK_NUMPAD8,
    VK_NUMPAD8_UP,
    VK_NUMPAD9,
    VK_NUMPAD9_PRIOR,
    VK_MULTIPLY,
    VK_MULTIPLY_MULTIVK,
    VK_ADD,
    VK_SEPARATOR,
    VK_SUBTRACT,
    VK_DECIMAL,
    VK_DECIMAL_DELETE,
    VK_DIVIDE,
    VK_F1,
    VK_F2,
    VK_F3,
    VK_F4,
    VK_F5,
    VK_F6,
    VK_F7,
    VK_F8,
    VK_F9,
    VK_F10,
    VK_F11,
    VK_F12,
    VK_F13,
    VK_F14,
    VK_F15,
    VK_F16,
    VK_F17,
    VK_F18,
    VK_F19,
    VK_F20,
    VK_F21,
    VK_F22,
    VK_F23,
    VK_F24,
    VK_NUMLOCK,
    VK_NUMLOCK_MULTIVK,
    VK_SCROLL,
    VK_SCROLL_MULTIVK,
    VK_OEM_NEC_EQUAL,
    VK_OEM_FJ_JISHO,
    VK_OEM_FJ_MASSHOU,
    VK_OEM_FJ_TOUROKU,
    VK_OEM_FJ_LOYA,
    VK_OEM_FJ_ROYA,
    VK_LSHIFT,
    VK_RSHIFT,
    VK_LCONTROL,
    VK_RCONTROL,
    VK_LMENU,
    VK_RMENU,
    VK_BROWSER_BACK,
    VK_BROWSER_FORWARD,
    VK_BROWSER_REFRESH,
    VK_BROWSER_STOP,
    VK_BROWSER_SEARCH,
    VK_BROWSER_FAVORITES,
    VK_BROWSER_HOME,
    VK_VOLUME_MUTE,
    VK_VOLUME_DOWN,
    VK_VOLUME_UP,
    VK_MEDIA_NEXT_TRACK,
    VK_MEDIA_PREV_TRACK,
    VK_MEDIA_STOP,
    VK_MEDIA_PLAY_PAUSE,
    VK_LAUNCH_MAIL,
    VK_LAUNCH_MEDIA_SELECT,
    VK_LAUNCH_APP1,
    VK_LAUNCH_APP2,
    VK_OEM_1,
    VK_OEM_PLUS,
    VK_OEM_COMMA,
    VK_OEM_MINUS,
    VK_OEM_PERIOD,
    VK_OEM_2,
    VK_OEM_3,
    VK_ABNT_C1,
    VK_ABNT_C2,
    VK_OEM_4,
    VK_OEM_5,
    VK_OEM_6,
    VK_OEM_7,
    VK_OEM_8,
    VK_OEM_AX,
    VK_OEM_102,
    VK_ICO_HELP,
    VK_ICO_00,
    VK_PROCESSKEY,
    VK_ICO_CLEAR,
    VK_PACKET,
    VK_OEM_RESET,
    VK_OEM_JUMP,
    VK_OEM_PA1,
    VK_OEM_PA2,
    VK_OEM_PA3,
    VK_OEM_WSCTRL,
    VK_OEM_CUSEL,
    VK_OEM_ATTN,
    VK_OEM_FINISH,
    VK_OEM_COPY,
    VK_OEM_AUTO,
    VK_OEM_ENLW,
    VK_OEM_BACKTAB,
    VK_ATTN,
    VK_CRSEL,
    VK_EXSEL,
    VK_EREOF,
    VK_PLAY,
    VK_ZOOM,
    VK_NONAME,
    VK_PA1,
    VK_OEM_CLEAR,
]

mappable = [
    VK_CANCEL,
    VK_BACK,
    VK_TAB,
    VK_CLEAR,
    VK_RETURN,
    VK_ESCAPE,
    VK_SPACE,
    VK_0,
    VK_1,
    VK_2,
    VK_3,
    VK_4,
    VK_5,
    VK_6,
    VK_7,
    VK_8,
    VK_9,
    VK_A,
    VK_B,
    VK_C,
    VK_D,
    VK_E,
    VK_F,
    VK_G,
    VK_H,
    VK_I,
    VK_J,
    VK_K,
    VK_L,
    VK_M,
    VK_N,
    VK_O,
    VK_P,
    VK_Q,
    VK_R,
    VK_S,
    VK_T,
    VK_U,
    VK_V,
    VK_W,
    VK_X,
    VK_Y,
    VK_Z,
    VK_NUMPAD0,
    VK_NUMPAD1,
    VK_NUMPAD2,
    VK_NUMPAD3,
    VK_NUMPAD4,
    VK_NUMPAD5,
    VK_NUMPAD6,
    VK_NUMPAD7,
    VK_NUMPAD8,
    VK_NUMPAD9,
    VK_MULTIPLY,
    VK_ADD,
    VK_SEPARATOR,
    VK_SUBTRACT,
    VK_DECIMAL,
    VK_DIVIDE,
    VK_OEM_NEC_EQUAL,
    VK_OEM_FJ_JISHO,
    VK_OEM_FJ_MASSHOU,
    VK_OEM_FJ_TOUROKU,
    VK_OEM_FJ_LOYA,
    VK_OEM_FJ_ROYA,
    VK_OEM_1,
    VK_OEM_PLUS,
    VK_OEM_COMMA,
    VK_OEM_MINUS,
    VK_OEM_PERIOD,
    VK_OEM_2,
    VK_OEM_3,
    VK_ABNT_C1,
    VK_ABNT_C2,
    VK_OEM_4,
    VK_OEM_5,
    VK_OEM_6,
    VK_OEM_7,
    VK_OEM_8,
    VK_OEM_AX,
    VK_OEM_102,
    VK_ICO_HELP,
    VK_PROCESSKEY,
    VK_ICO_CLEAR,
    VK_PACKET,
    VK_OEM_RESET,
    VK_OEM_JUMP,
    VK_OEM_PA1,
    VK_OEM_PA2,
    VK_OEM_PA3,
    VK_OEM_WSCTRL,
    VK_OEM_CUSEL,
    VK_OEM_ATTN,
    VK_OEM_FINISH,
    VK_OEM_COPY,
    VK_OEM_AUTO,
    VK_OEM_ENLW,
    VK_OEM_BACKTAB,
    VK_ATTN,
    VK_CRSEL,
    VK_EXSEL,
    VK_EREOF,
    VK_PLAY,
    VK_ZOOM,
    VK_NONAME,
    VK_PA1,
    VK_OEM_CLEAR,
]

name_to_vk = {
    "VK__end_": VK__end_,
    "VK_LBUTTON": VK_LBUTTON,
    "VK_RBUTTON": VK_RBUTTON,
    "VK_CANCEL": VK_CANCEL,
    "VK_MBUTTON": VK_MBUTTON,
    "VK_XBUTTON1": VK_XBUTTON1,
    "VK_XBUTTON2": VK_XBUTTON2,
    "VK_BACK": VK_BACK,
    "VK_TAB": VK_TAB,
    "VK_CLEAR": VK_CLEAR,
    "VK_RETURN": VK_RETURN,
    "VK_SHIFT": VK_SHIFT,
    "VK_CONTROL": VK_CONTROL,
    "VK_MENU": VK_MENU,
    "VK_PAUSE": VK_PAUSE,
    "VK_PAUSE_MULTIVK": VK_PAUSE_MULTIVK,
    "VK_CAPITAL": VK_CAPITAL,
    "VK_KANA": VK_KANA,
    "VK_HANGEUL": VK_HANGEUL,
    "VK_HANGUL": VK_HANGUL,
    "VK_IME_ON": VK_IME_ON,
    "VK_JUNJA": VK_JUNJA,
    "VK_FINAL": VK_FINAL,
    "VK_HANJA": VK_HANJA,
    "VK_KANJI": VK_KANJI,
    "VK_IME_OFF": VK_IME_OFF,
    "VK_ESCAPE": VK_ESCAPE,
    "VK_CONVERT": VK_CONVERT,
    "VK_NONCONVERT": VK_NONCONVERT,
    "VK_ACCEPT": VK_ACCEPT,
    "VK_MODECHANGE": VK_MODECHANGE,
    "VK_SPACE": VK_SPACE,
    "VK_PRIOR": VK_PRIOR,
    "VK_NEXT": VK_NEXT,
    "VK_END": VK_END,
    "VK_HOME": VK_HOME,
    "VK_LEFT": VK_LEFT,
    "VK_UP": VK_UP,
    "VK_RIGHT": VK_RIGHT,
    "VK_DOWN": VK_DOWN,
    "VK_SELECT": VK_SELECT,
    "VK_PRINT": VK_PRINT,
    "VK_EXECUTE": VK_EXECUTE,
    "VK_SNAPSHOT": VK_SNAPSHOT,
    "VK_INSERT": VK_INSERT,
    "VK_DELETE": VK_DELETE,
    "VK_HELP": VK_HELP,
    "VK_0": VK_0,
    "VK_1": VK_1,
    "VK_2": VK_2,
    "VK_3": VK_3,
    "VK_4": VK_4,
    "VK_5": VK_5,
    "VK_6": VK_6,
    "VK_7": VK_7,
    "VK_8": VK_8,
    "VK_9": VK_9,
    "VK_A": VK_A,
    "VK_B": VK_B,
    "VK_C": VK_C,
    "VK_D": VK_D,
    "VK_E": VK_E,
    "VK_F": VK_F,
    "VK_G": VK_G,
    "VK_H": VK_H,
    "VK_I": VK_I,
    "VK_J": VK_J,
    "VK_K": VK_K,
    "VK_L": VK_L,
    "VK_M": VK_M,
    "VK_N": VK_N,
    "VK_O": VK_O,
    "VK_P": VK_P,
    "VK_Q": VK_Q,
    "VK_R": VK_R,
    "VK_S": VK_S,
    "VK_T": VK_T,
    "VK_U": VK_U,
    "VK_V": VK_V,
    "VK_W": VK_W,
    "VK_X": VK_X,
    "VK_Y": VK_Y,
    "VK_Z": VK_Z,
    "VK_LWIN": VK_LWIN,
    "VK_RWIN": VK_RWIN,
    "VK_APPS": VK_APPS,
    "VK_SLEEP": VK_SLEEP,
    "VK_NUMPAD0": VK_NUMPAD0,
    "VK_NUMPAD0_INSERT": VK_NUMPAD0_INSERT,
    "VK_NUMPAD1": VK_NUMPAD1,
    "VK_NUMPAD1_END": VK_NUMPAD1_END,
    "VK_NUMPAD2": VK_NUMPAD2,
    "VK_NUMPAD2_DOWN": VK_NUMPAD2_DOWN,
    "VK_NUMPAD3": VK_NUMPAD3,
    "VK_NUMPAD3_NEXT": VK_NUMPAD3_NEXT,
    "VK_NUMPAD4": VK_NUMPAD4,
    "VK_NUMPAD4_LEFT": VK_NUMPAD4_LEFT,
    "VK_NUMPAD5": VK_NUMPAD5,
    "VK_NUMPAD5_CLEAR": VK_NUMPAD5_CLEAR,
    "VK_NUMPAD6": VK_NUMPAD6,
    "VK_NUMPAD6_RIGHT": VK_NUMPAD6_RIGHT,
    "VK_NUMPAD7": VK_NUMPAD7,
    "VK_NUMPAD7_HOME": VK_NUMPAD7_HOME,
    "VK_NUMPAD8": VK_NUMPAD8,
    "VK_NUMPAD8_UP": VK_NUMPAD8_UP,
    "VK_NUMPAD9": VK_NUMPAD9,
    "VK_NUMPAD9_PRIOR": VK_NUMPAD9_PRIOR,
    "VK_MULTIPLY": VK_MULTIPLY,
    "VK_MULTIPLY_MULTIVK": VK_MULTIPLY_MULTIVK,
    "VK_ADD": VK_ADD,
    "VK_SEPARATOR": VK_SEPARATOR,
    "VK_SUBTRACT": VK_SUBTRACT,
    "VK_DECIMAL": VK_DECIMAL,
    "VK_DECIMAL_DELETE": VK_DECIMAL_DELETE,
    "VK_DIVIDE": VK_DIVIDE,
    "VK_F1": VK_F1,
    "VK_F2": VK_F2,
    "VK_F3": VK_F3,
    "VK_F4": VK_F4,
    "VK_F5": VK_F5,
    "VK_F6": VK_F6,
    "VK_F7": VK_F7,
    "VK_F8": VK_F8,
    "VK_F9": VK_F9,
    "VK_F10": VK_F10,
    "VK_F11": VK_F11,
    "VK_F12": VK_F12,
    "VK_F13": VK_F13,
    "VK_F14": VK_F14,
    "VK_F15": VK_F15,
    "VK_F16": VK_F16,
    "VK_F17": VK_F17,
    "VK_F18": VK_F18,
    "VK_F19": VK_F19,
    "VK_F20": VK_F20,
    "VK_F21": VK_F21,
    "VK_F22": VK_F22,
    "VK_F23": VK_F23,
    "VK_F24": VK_F24,
    "VK_NAVIGATION_VIEW": VK_NAVIGATION_VIEW,
    "VK_NAVIGATION_MENU": VK_NAVIGATION_MENU,
    "VK_NAVIGATION_UP": VK_NAVIGATION_UP,
    "VK_NAVIGATION_DOWN": VK_NAVIGATION_DOWN,
    "VK_NAVIGATION_LEFT": VK_NAVIGATION_LEFT,
    "VK_NAVIGATION_RIGHT": VK_NAVIGATION_RIGHT,
    "VK_NAVIGATION_ACCEPT": VK_NAVIGATION_ACCEPT,
    "VK_NAVIGATION_CANCEL": VK_NAVIGATION_CANCEL,
    "VK_NUMLOCK": VK_NUMLOCK,
    "VK_NUMLOCK_MULTIVK": VK_NUMLOCK_MULTIVK,
    "VK_SCROLL": VK_SCROLL,
    "VK_SCROLL_MULTIVK": VK_SCROLL_MULTIVK,
    "VK_OEM_NEC_EQUAL": VK_OEM_NEC_EQUAL,
    "VK_OEM_FJ_JISHO": VK_OEM_FJ_JISHO,
    "VK_OEM_FJ_MASSHOU": VK_OEM_FJ_MASSHOU,
    "VK_OEM_FJ_TOUROKU": VK_OEM_FJ_TOUROKU,
    "VK_OEM_FJ_LOYA": VK_OEM_FJ_LOYA,
    "VK_OEM_FJ_ROYA": VK_OEM_FJ_ROYA,
    "VK_LSHIFT": VK_LSHIFT,
    "VK_RSHIFT": VK_RSHIFT,
    "VK_LCONTROL": VK_LCONTROL,
    "VK_RCONTROL": VK_RCONTROL,
    "VK_LMENU": VK_LMENU,
    "VK_RMENU": VK_RMENU,
    "VK_BROWSER_BACK": VK_BROWSER_BACK,
    "VK_BROWSER_FORWARD": VK_BROWSER_FORWARD,
    "VK_BROWSER_REFRESH": VK_BROWSER_REFRESH,
    "VK_BROWSER_STOP": VK_BROWSER_STOP,
    "VK_BROWSER_SEARCH": VK_BROWSER_SEARCH,
    "VK_BROWSER_FAVORITES": VK_BROWSER_FAVORITES,
    "VK_BROWSER_HOME": VK_BROWSER_HOME,
    "VK_VOLUME_MUTE": VK_VOLUME_MUTE,
    "VK_VOLUME_DOWN": VK_VOLUME_DOWN,
    "VK_VOLUME_UP": VK_VOLUME_UP,
    "VK_MEDIA_NEXT_TRACK": VK_MEDIA_NEXT_TRACK,
    "VK_MEDIA_PREV_TRACK": VK_MEDIA_PREV_TRACK,
    "VK_MEDIA_STOP": VK_MEDIA_STOP,
    "VK_MEDIA_PLAY_PAUSE": VK_MEDIA_PLAY_PAUSE,
    "VK_LAUNCH_MAIL": VK_LAUNCH_MAIL,
    "VK_LAUNCH_MEDIA_SELECT": VK_LAUNCH_MEDIA_SELECT,
    "VK_LAUNCH_APP1": VK_LAUNCH_APP1,
    "VK_LAUNCH_APP2": VK_LAUNCH_APP2,
    "VK_OEM_1": VK_OEM_1,
    "VK_OEM_PLUS": VK_OEM_PLUS,
    "VK_OEM_COMMA": VK_OEM_COMMA,
    "VK_OEM_MINUS": VK_OEM_MINUS,
    "VK_OEM_PERIOD": VK_OEM_PERIOD,
    "VK_OEM_2": VK_OEM_2,
    "VK_OEM_3": VK_OEM_3,
    "VK_ABNT_C1": VK_ABNT_C1,
    "VK_ABNT_C2": VK_ABNT_C2,
    "VK_GAMEPAD_A": VK_GAMEPAD_A,
    "VK_GAMEPAD_B": VK_GAMEPAD_B,
    "VK_GAMEPAD_X": VK_GAMEPAD_X,
    "VK_GAMEPAD_Y": VK_GAMEPAD_Y,
    "VK_GAMEPAD_RIGHT_SHOULDER": VK_GAMEPAD_RIGHT_SHOULDER,
    "VK_GAMEPAD_LEFT_SHOULDER": VK_GAMEPAD_LEFT_SHOULDER,
    "VK_GAMEPAD_LEFT_TRIGGER": VK_GAMEPAD_LEFT_TRIGGER,
    "VK_GAMEPAD_RIGHT_TRIGGER": VK_GAMEPAD_RIGHT_TRIGGER,
    "VK_GAMEPAD_DPAD_UP": VK_GAMEPAD_DPAD_UP,
    "VK_GAMEPAD_DPAD_DOWN": VK_GAMEPAD_DPAD_DOWN,
    "VK_GAMEPAD_DPAD_LEFT": VK_GAMEPAD_DPAD_LEFT,
    "VK_GAMEPAD_DPAD_RIGHT": VK_GAMEPAD_DPAD_RIGHT,
    "VK_GAMEPAD_MENU": VK_GAMEPAD_MENU,
    "VK_GAMEPAD_VIEW": VK_GAMEPAD_VIEW,
    "VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON": VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON,
    "VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON": VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
    "VK_GAMEPAD_LEFT_THUMBSTICK_UP": VK_GAMEPAD_LEFT_THUMBSTICK_UP,
    "VK_GAMEPAD_LEFT_THUMBSTICK_DOWN": VK_GAMEPAD_LEFT_THUMBSTICK_DOWN,
    "VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT": VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT,
    "VK_GAMEPAD_LEFT_THUMBSTICK_LEFT": VK_GAMEPAD_LEFT_THUMBSTICK_LEFT,
    "VK_GAMEPAD_RIGHT_THUMBSTICK_UP": VK_GAMEPAD_RIGHT_THUMBSTICK_UP,
    "VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN": VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN,
    "VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT": VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT,
    "VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT": VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT,
    "VK_OEM_4": VK_OEM_4,
    "VK_OEM_5": VK_OEM_5,
    "VK_OEM_6": VK_OEM_6,
    "VK_OEM_7": VK_OEM_7,
    "VK_OEM_8": VK_OEM_8,
    "VK_OEM_AX": VK_OEM_AX,
    "VK_OEM_102": VK_OEM_102,
    "VK_ICO_HELP": VK_ICO_HELP,
    "VK_ICO_00": VK_ICO_00,
    "VK_PROCESSKEY": VK_PROCESSKEY,
    "VK_ICO_CLEAR": VK_ICO_CLEAR,
    "VK_PACKET": VK_PACKET,
    "VK_OEM_RESET": VK_OEM_RESET,
    "VK_OEM_JUMP": VK_OEM_JUMP,
    "VK_OEM_PA1": VK_OEM_PA1,
    "VK_OEM_PA2": VK_OEM_PA2,
    "VK_OEM_PA3": VK_OEM_PA3,
    "VK_OEM_WSCTRL": VK_OEM_WSCTRL,
    "VK_OEM_CUSEL": VK_OEM_CUSEL,
    "VK_OEM_ATTN": VK_OEM_ATTN,
    "VK_OEM_FINISH": VK_OEM_FINISH,
    "VK_OEM_COPY": VK_OEM_COPY,
    "VK_OEM_AUTO": VK_OEM_AUTO,
    "VK_OEM_ENLW": VK_OEM_ENLW,
    "VK_OEM_BACKTAB": VK_OEM_BACKTAB,
    "VK_ATTN": VK_ATTN,
    "VK_CRSEL": VK_CRSEL,
    "VK_EXSEL": VK_EXSEL,
    "VK_EREOF": VK_EREOF,
    "VK_PLAY": VK_PLAY,
    "VK_ZOOM": VK_ZOOM,
    "VK_NONAME": VK_NONAME,
    "VK_PA1": VK_PA1,
    "VK_OEM_CLEAR": VK_OEM_CLEAR,
    "VK__none_": VK__none_,
}

code_to_vk = {
    0x0: VK__end_,
    0x1: VK_LBUTTON,
    0x2: VK_RBUTTON,
    0x3: VK_CANCEL,
    0x4: VK_MBUTTON,
    0x5: VK_XBUTTON1,
    0x6: VK_XBUTTON2,
    0x8: VK_BACK,
    0x9: VK_TAB,
    0xc: VK_CLEAR,
    0xd: VK_RETURN,
    0x10: VK_SHIFT,
    0x11: VK_CONTROL,
    0x12: VK_MENU,
    0x13: VK_PAUSE,
    0x213: VK_PAUSE_MULTIVK,
    0x14: VK_CAPITAL,
    0x15: VK_KANA,
    0x16: VK_IME_ON,
    0x17: VK_JUNJA,
    0x18: VK_FINAL,
    0x19: VK_HANJA,
    0x1a: VK_IME_OFF,
    0x1b: VK_ESCAPE,
    0x1c: VK_CONVERT,
    0x1d: VK_NONCONVERT,
    0x1e: VK_ACCEPT,
    0x1f: VK_MODECHANGE,
    0x20: VK_SPACE,
    0x21: VK_PRIOR,
    0x22: VK_NEXT,
    0x23: VK_END,
    0x24: VK_HOME,
    0x25: VK_LEFT,
    0x26: VK_UP,
    0x27: VK_RIGHT,
    0x28: VK_DOWN,
    0x29: VK_SELECT,
    0x2a: VK_PRINT,
    0x2b: VK_EXECUTE,
    0x2c: VK_SNAPSHOT,
    0x2d: VK_INSERT,
    0x2e: VK_DELETE,
    0x2f: VK_HELP,
    0x30: VK_0,
    0x31: VK_1,
    0x32: VK_2,
    0x33: VK_3,
    0x34: VK_4,
    0x35: VK_5,
    0x36: VK_6,
    0x37: VK_7,
    0x38: VK_8,
    0x39: VK_9,
    0x41: VK_A,
    0x42: VK_B,
    0x43: VK_C,
    0x44: VK_D,
    0x45: VK_E,
    0x46: VK_F,
    0x47: VK_G,
    0x48: VK_H,
    0x49: VK_I,
    0x4a: VK_J,
    0x4b: VK_K,
    0x4c: VK_L,
    0x4d: VK_M,
    0x4e: VK_N,
    0x4f: VK_O,
    0x50: VK_P,
    0x51: VK_Q,
    0x52: VK_R,
    0x53: VK_S,
    0x54: VK_T,
    0x55: VK_U,
    0x56: VK_V,
    0x57: VK_W,
    0x58: VK_X,
    0x59: VK_Y,
    0x5a: VK_Z,
    0x5b: VK_LWIN,
    0x5c: VK_RWIN,
    0x5d: VK_APPS,
    0x5f: VK_SLEEP,
    0x60: VK_NUMPAD0,
    0xc2d: VK_NUMPAD0_INSERT,
    0x61: VK_NUMPAD1,
    0xc23: VK_NUMPAD1_END,
    0x62: VK_NUMPAD2,
    0xc28: VK_NUMPAD2_DOWN,
    0x63: VK_NUMPAD3,
    0xc22: VK_NUMPAD3_NEXT,
    0x64: VK_NUMPAD4,
    0xc25: VK_NUMPAD4_LEFT,
    0x65: VK_NUMPAD5,
    0xc0c: VK_NUMPAD5_CLEAR,
    0x66: VK_NUMPAD6,
    0xc27: VK_NUMPAD6_RIGHT,
    0x67: VK_NUMPAD7,
    0xc24: VK_NUMPAD7_HOME,
    0x68: VK_NUMPAD8,
    0xc26: VK_NUMPAD8_UP,
    0x69: VK_NUMPAD9,
    0xc21: VK_NUMPAD9_PRIOR,
    0x6a: VK_MULTIPLY,
    0x26a: VK_MULTIPLY_MULTIVK,
    0x6b: VK_ADD,
    0x6c: VK_SEPARATOR,
    0x6d: VK_SUBTRACT,
    0x6e: VK_DECIMAL,
    0xc2e: VK_DECIMAL_DELETE,
    0x6f: VK_DIVIDE,
    0x70: VK_F1,
    0x71: VK_F2,
    0x72: VK_F3,
    0x73: VK_F4,
    0x74: VK_F5,
    0x75: VK_F6,
    0x76: VK_F7,
    0x77: VK_F8,
    0x78: VK_F9,
    0x79: VK_F10,
    0x7a: VK_F11,
    0x7b: VK_F12,
    0x7c: VK_F13,
    0x7d: VK_F14,
    0x7e: VK_F15,
    0x7f: VK_F16,
    0x80: VK_F17,
    0x81: VK_F18,
    0x82: VK_F19,
    0x83: VK_F20,
    0x84: VK_F21,
    0x85: VK_F22,
    0x86: VK_F23,
    0x87: VK_F24,
    0x88: VK_NAVIGATION_VIEW,
    0x89: VK_NAVIGATION_MENU,
    0x8a: VK_NAVIGATION_UP,
    0x8b: VK_NAVIGATION_DOWN,
    0x8c: VK_NAVIGATION_LEFT,
    0x8d: VK_NAVIGATION_RIGHT,
    0x8e: VK_NAVIGATION_ACCEPT,
    0x8f: VK_NAVIGATION_CANCEL,
    0x90: VK_NUMLOCK,
    0x290: VK_NUMLOCK_MULTIVK,
    0x91: VK_SCROLL,
    0x291: VK_SCROLL_MULTIVK,
    0x92: VK_OEM_NEC_EQUAL,
    0x93: VK_OEM_FJ_MASSHOU,
    0x94: VK_OEM_FJ_TOUROKU,
    0x95: VK_OEM_FJ_LOYA,
    0x96: VK_OEM_FJ_ROYA,
    0xa0: VK_LSHIFT,
    0xa1: VK_RSHIFT,
    0xa2: VK_LCONTROL,
    0xa3: VK_RCONTROL,
    0xa4: VK_LMENU,
    0xa5: VK_RMENU,
    0xa6: VK_BROWSER_BACK,
    0xa7: VK_BROWSER_FORWARD,
    0xa8: VK_BROWSER_REFRESH,
    0xa9: VK_BROWSER_STOP,
    0xaa: VK_BROWSER_SEARCH,
    0xab: VK_BROWSER_FAVORITES,
    0xac: VK_BROWSER_HOME,
    0xad: VK_VOLUME_MUTE,
    0xae: VK_VOLUME_DOWN,
    0xaf: VK_VOLUME_UP,
    0xb0: VK_MEDIA_NEXT_TRACK,
    0xb1: VK_MEDIA_PREV_TRACK,
    0xb2: VK_MEDIA_STOP,
    0xb3: VK_MEDIA_PLAY_PAUSE,
    0xb4: VK_LAUNCH_MAIL,
    0xb5: VK_LAUNCH_MEDIA_SELECT,
    0xb6: VK_LAUNCH_APP1,
    0xb7: VK_LAUNCH_APP2,
    0xba: VK_OEM_1,
    0xbb: VK_OEM_PLUS,
    0xbc: VK_OEM_COMMA,
    0xbd: VK_OEM_MINUS,
    0xbe: VK_OEM_PERIOD,
    0xbf: VK_OEM_2,
    0xc0: VK_OEM_3,
    0xc1: VK_ABNT_C1,
    0xc2: VK_ABNT_C2,
    0xc3: VK_GAMEPAD_A,
    0xc4: VK_GAMEPAD_B,
    0xc5: VK_GAMEPAD_X,
    0xc6: VK_GAMEPAD_Y,
    0xc7: VK_GAMEPAD_RIGHT_SHOULDER,
    0xc8: VK_GAMEPAD_LEFT_SHOULDER,
    0xc9: VK_GAMEPAD_LEFT_TRIGGER,
    0xca: VK_GAMEPAD_RIGHT_TRIGGER,
    0xcb: VK_GAMEPAD_DPAD_UP,
    0xcc: VK_GAMEPAD_DPAD_DOWN,
    0xcd: VK_GAMEPAD_DPAD_LEFT,
    0xce: VK_GAMEPAD_DPAD_RIGHT,
    0xcf: VK_GAMEPAD_MENU,
    0xd0: VK_GAMEPAD_VIEW,
    0xd1: VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON,
    0xd2: VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
    0xd3: VK_GAMEPAD_LEFT_THUMBSTICK_UP,
    0xd4: VK_GAMEPAD_LEFT_THUMBSTICK_DOWN,
    0xd5: VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT,
    0xd6: VK_GAMEPAD_LEFT_THUMBSTICK_LEFT,
    0xd7: VK_GAMEPAD_RIGHT_THUMBSTICK_UP,
    0xd8: VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN,
    0xd9: VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT,
    0xda: VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT,
    0xdb: VK_OEM_4,
    0xdc: VK_OEM_5,
    0xdd: VK_OEM_6,
    0xde: VK_OEM_7,
    0xdf: VK_OEM_8,
    0xe1: VK_OEM_AX,
    0xe2: VK_OEM_102,
    0xe3: VK_ICO_HELP,
    0xe4: VK_ICO_00,
    0xe5: VK_PROCESSKEY,
    0xe6: VK_ICO_CLEAR,
    0xe7: VK_PACKET,
    0xe9: VK_OEM_RESET,
    0xea: VK_OEM_JUMP,
    0xeb: VK_OEM_PA1,
    0xec: VK_OEM_PA2,
    0xed: VK_OEM_PA3,
    0xee: VK_OEM_WSCTRL,
    0xef: VK_OEM_CUSEL,
    0xf0: VK_OEM_ATTN,
    0xf1: VK_OEM_FINISH,
    0xf2: VK_OEM_COPY,
    0xf3: VK_OEM_AUTO,
    0xf4: VK_OEM_ENLW,
    0xf5: VK_OEM_BACKTAB,
    0xf6: VK_ATTN,
    0xf7: VK_CRSEL,
    0xf8: VK_EXSEL,
    0xf9: VK_EREOF,
    0xfa: VK_PLAY,
    0xfb: VK_ZOOM,
    0xfc: VK_NONAME,
    0xfd: VK_PA1,
    0xfe: VK_OEM_CLEAR,
    0xff: VK__none_,
}

_translation = {3117: 96, 3107: 97, 3112: 98, 3106: 99, 3109: 100, 3084: 101, 3111: 102, 3108: 103, 3110: 104, 3105: 105, 3118: 110, 656: 144, 657: 145, 618: 106, 531: 19}
_translation_reverse = {96: 3117, 97: 3107, 98: 3112, 99: 3106, 100: 3109, 101: 3084, 102: 3111, 103: 3108, 104: 3110, 105: 3105, 110: 3118, 144: 656, 145: 657, 106: 618, 19: 531}
